name: Cart Test Suite
on: workflow_call

jobs:
  cart-chrome-tests:
    name: Cart Tests (Chrome)
    uses: ./.github/workflows/web-test-ci.yml
    with:
      browser-name: chrome
      test-directory: 'tests/cart'
      report-prefix: 'reports/TestCart'
      html-report-name: 'cart-chrome-report'

  cart-edge-tests:
    name: Cart Tests (Edge)
    uses: ./.github/workflows/web-test-ci.yml
    with:
      browser-name: edge
      test-directory: 'tests/cart'
      report-prefix: 'reports/TestCart'
      html-report-name: 'cart-edge-report'

  cart-firefox-tests:
    name: Cart Tests (Firefox)
    uses: ./.github/workflows/web-test-ci.yml
    with:
      browser-name: firefox
      test-directory: 'tests/cart'
      report-prefix: 'reports/TestCart'
      html-report-name: 'cart-firefox-report'